<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    <CentralPackageTransitivePinningEnabled>true</CentralPackageTransitivePinningEnabled>
    <RestorePackagesWithLockFile>true</RestorePackagesWithLockFile>
  </PropertyGroup>
  <ItemGroup Label="Runtime">
    <PackageVersion Include="Microsoft.ApplicationInsights" Version="2.23.0" />
    <PackageVersion Include="NLog" Version="5.5.0" />
    <PackageVersion Include="System.Text.Json" Version="8.0.5" />
  </ItemGroup>
  <ItemGroup Label="Test">
    <PackageVersion Include="WireMock.Net" Version="1.6.9" />
  </ItemGroup>
</Project>