<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    <CentralPackageTransitivePinningEnabled>true</CentralPackageTransitivePinningEnabled>
    <RestorePackagesWithLockFile>true</RestorePackagesWithLockFile>
  </PropertyGroup>
  <ItemGroup Label="Runtime">
    <PackageVersion Include="Microsoft.ApplicationInsights" Version="[2.23.0]" />
    <PackageVersion Include="NLog" Version="6.2.0" />
    <PackageVersion Include="System.Text.Json" Version="10.0.10" />
  </ItemGroup>
  <ItemGroup Label="Test">
    <PackageVersion Include="WireMock.Net" Version="2.15.0" />
    <PackageVersion Include="Microsoft.Testing.Extensions.CodeCoverage" Version="18.9.0" />
    <PackageVersion Include="JsonConverter.Abstractions" Version="0.13.0" />
  </ItemGroup>
</Project>
